name: Update GitHub Profile Page
on: [push]

jobs:
  gadpp_job:
    runs-on: ubuntu-latest
    name: Update GitHub Profile Page
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: GADPP
        uses: umutphp/github-action-dynamic-profile-page@v5
        id: gadpp
        env:
          API_TOKEN_GITHUB: ${{ secrets.API_TOKEN_GITHUB }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          github-username: 'Luyue28'
          user-email: 'zhan0067@hz.nl'
          readme-file: 'README.md'

      - name: Push changes
        run: |
          git config --global user.name "Your Name"
          git config --global user.email "zhan0067@hz.nl"
          git add README.md
          git commit -m "Update README with new content" || echo "No changes to commit"
          git push origin main
