name: Update Special Repository

on:
  push:
    branches:
      - main

jobs:
  update-readme:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout main repository
        uses: actions/checkout@v2

      - name: Update README
        run: |
          echo "Updated on $(date) with commit message: ${{ github.event.head_commit.message }}" >> README.md

      - name: Commit changes
        run: |
          git config --global user.name "Luyue28"
          git config --global user.email "zhan0067@hz.nl"
          git add README.md
          git commit -m "Update README with latest commit info" || echo "No changes to commit"

      - name: Push changes to special repository
        run: |
          git push https://x-access-token:${{ secrets.API_TOKEN_GITHUB }}@github.com/Luyue28/Luyue28.git main
