name: Update GitHub Profile Page

on:
  push:
    branches:
      - main

jobs:
  update-profile:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Update README
        run: |
          echo "Updated on $(date)" >> README.md

      - name: Commit changes
        run: |
          git config --global user.name "Your Name"
          git config --global user.email "zhan0067@hz.nl"
          git add README.md
          git commit -m "Update README with new commit info" || echo "No changes to commit"

      - name: Push changes
        env:
          API_TOKEN_GITHUB: ${{ secrets.API_TOKEN_GITHUB }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git push https://x-access-token:${{ secrets.API_TOKEN_GITHUB }}@github.com/Luyue28/Luyue28.git main
